### ISSUE TITLE
Never storing session token

### ISSUE THREAD

**Issue by drexel-ue** [clerk/clerk-sdk-flutter#67]
### Steps to reproduce

1. sign into flutter app using clerk auth widget with LinkedIn auth
2. success
3. restart app
4. will need to sign in again

### Expected results

should remember last session and show authenticated ui

### Actual results

showing unauthenticated ui upon restart after successful authentication

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:clerk_auth/clerk_auth.dart';
import 'package:clerk_flutter/clerk_flutter.dart';
import 'package:flutter/material.dart';

void main() {
  const clerkPublishableKey = String.fromEnvironment('CLERK_PUBLISHABLE_KEY');
  runApp(const ClerkAuthTestApp(
    clerkPublishableKey: clerkPublishableKey,
  ));
}

class ClerkAuthTestApp extends StatefulWidget {
  const ClerkAuthTestApp({
    super.key,
    required this.clerkPublishableKey,
  });

  final String clerkPublishableKey;

  @override
  State<ClerkAuthTestApp> createState() => _ClerkAuthTestAppState();
}

class _ClerkAuthTestAppState extends State<ClerkAuthTestApp> {
  StreamSubscription<AuthError>? _authErrorSub;
  Session? _session;
  String? _token;

  void _reactToAuthBuilder(ClerkAuthProvider auth) {
    _authErrorSub ??= auth.errorStream.listen(_authErrorListener);
    _setSession(auth.client.activeSession);
  }

  void _setSession(Session? session) {
    _session = session;
    _token = _session?.lastActiveToken?.jwt;
    print('==========NEW SESSION:\nid: ${session?.id}\ntoken: $_token');
  }

  void _authErrorListener(AuthError authError) {
    print('=========AUTH ERROR: ${authError.message}');
  }

  @override
  void dispose() {
    _authErrorSub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ClerkAuth(
      publishableKey: widget.clerkPublishableKey,
      child: MaterialApp(
        home: Scaffold(
          body: ClerkAuthBuilder(
            signedInBuilder: (context, auth) {
              _reactToAuthBuilder(auth);
              return const ClerkUserButton();
            },
            signedOutBuilder: (context, auth) {
              _reactToAuthBuilder(auth);
              return const ClerkAuthenticationWidget();
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
FormatException (FormatException: Invalid length, must be multiple of four (at character 263)
...wNktiN3ZCQUZUUGJDIiwic3ViIjoidXNlcl8ycURPNFVXY0F0TjZhWjVCWFJSQ3J0S1FVQ3UifQ
                                                                              ^
)

#0      _Base64Decoder.close (dart:convert/base64.dart:639:7)
#1      Base64Decoder.convert (dart:convert/base64.dart:510:13)
#2      Base64Codec.decode (dart:convert/base64.dart:83:47)
#3      TokenCache.sessionToken= (package:clerk_auth/src/clerk_api/token_cache.dart:131:57)
#4      TokenCache.updateFrom (package:clerk_auth/src/clerk_api/token_cache.dart:159:48)
#5      Api._fetchApiResponse (package:clerk_auth/src/clerk_api/api.dart:537:21)
<asynchronous suspension>
#6      Auth._housekeeping (package:clerk_auth/src/clerk_auth/auth.dart:108:3)
<asynchronous suspension>
#7      Auth.transfer (package:clerk_auth/src/clerk_auth/auth.dart:127:5)
<asynchronous suspension>
#8      ClerkAuthProvider.call (package:clerk_flutter/src/widgets/control/clerk_auth_provider.dart:125:16)
<asynchronous suspension>
#9      ClerkAuthProvider.sso (package:clerk_flutter/src/widgets/control/clerk_auth_provider.dart:101:13)
<asynchronous suspension>

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.7 23H124 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/ikkeshpack/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ikkeshpack/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/ikkeshpack/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • IKesh’s iPhone (mobile)         • 00008140-001240990A33001C • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.7 23H124 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by EdwardRodr1guez** [comment]
Adiotionally ` Clerkauthbuilder` counts with other parameter different from signedInBuilder y signedOutBuilder which is intended to handle success existing sessing tokens however never works. As @drexel-ue mentions, when user restart the app is necessary to re-sign in

**Comment by shinyford** [comment]
I cannot duplicate this. @drexel-ue Could you please re-test with the latest build (once it's merged to main, anyway)

**Comment by shinyford** [comment]
I'm going to say this is fixed now. Let me know if it's not.
